{% set name = "g2clib" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 73afba9da382fed73ed8692d77fa037bb313280879cd4012a5e5697dccf55175

build:
  skip: true  # [win]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - pkg-config >=0.21
    - make                  # [not win]
    - ninja                 # [win]
  host:
    - libpng
    - zlib
    - jasper

test:
  commands:
    - test -f ${PREFIX}/lib/libg2c${SHLIB_EXT}  # [not win]
    - test ! -f ${PREFIX}/lib/libg2c.a  # [not win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-g2c
  summary: This library contains C decoder/encoder routines for GRIB edition 2.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
    - xylar
    - timcera
    - EricEngle-NOAA
