{% set name = "g2clib" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v{{ version }}.tar.gz

build:
  script: 
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=${PREFIX} ..
    - make
    - make test
    - make install
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cmake
  host:
    - libpng
    - zlib
    - jasper
  run:
    - libpng
    - zlib
    - jasper

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-g2c
  summary: This library contains C decoder/encoder routines for GRIB edition 2.
  license: LGPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - timcera
