{% set name = "nceplibs-g2c" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4ce9f5a7cb0950699fe08ebc5a463ab4d09ef550c050391a319308a2494f971f

build:
  skip: true  # [win]
  number: 4

outputs:
  - name: {{ name }}
    script: install_nceplibs_g2c.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
        - pkg-config >=0.21
        - make                  # [not win]
        - ninja                 # [win]
      host:
        - libpng
        - zlib
        - libaec >=1.0.6
        - openjpeg

    test:
      commands:
        - test -f ${PREFIX}/lib/libg2c${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libg2c.a  # [not win]

  # old name for the package
  - name: g2clib
    requirements:
      run:
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
    test:
      commands:
        - test -f ${PREFIX}/lib/libg2c${SHLIB_EXT}  # [not win]
        - test ! -f ${PREFIX}/lib/libg2c.a  # [not win]

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-g2c
  summary: This library contains C decoder/encoder routines for GRIB edition 2.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
    - jhamman
    - xylar
    - timcera
    - EricEngle-NOAA
