{% set name = "g2clib" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NOAA-EMC/NCEPLIBS-g2c/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 73afba9da382fed73ed8692d77fa037bb313280879cd4012a5e5697dccf55175

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - pkg-config >=0.21  # [not win]
    - make  # [not win]
    - ninja  # [win]
  host:
    - libpng
    - zlib
    - jasper >=2.0.25
  run:
    - libpng
    - zlib
    - jasper >=2.0.25

about:
  home: https://github.com/NOAA-EMC/NCEPLIBS-g2c
  summary: This library contains C decoder/encoder routines for GRIB edition 2.
  license: LGPL-3.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - timcera
