travis:
  secure:
    BINSTAR_TOKEN: QG8VEpzFb3JDqbSrzBP+W43Q3bZxXsAJWTylTFikFkGkjGA1Ukfyi4JnUtZWppUmAVG1m8vrvG1GqI6edYPLlm8DTVskhcsfysUavypsAF9Xmq5MKVnzVJKSV+HP/K3hS7lnJZPt9Px3OznsKV7jkzVKhXR6mS5/v2106+1yXmIAu40KDNwZXxG4xDB+dx3G/d87Cb68IRaKdxcCBCnKECvCTRbU+XFQMcgkGvD2q7eXYZ0nMwy1xThB9DL7+xYNwR8qGwo3Byud1pxPUzVGNaaPX0lgbr6cnIMVSmSAEd/FQywnbj0Rl/jsMSHXOkv150SM/EEvIy1Snuu1aAmrhgsMVwLTXvS+fWJqct6IAk2kPMUupEDB4Imd49hm7RE5SBhctOD+6yGrusFkcghSWMRlR7ninno1BKqPHs9sCv0d3z4PWvN2JzujxzWFIsFjZEZxKI3hK41nTFsFwFkmhDKMVyi2676lnOR4Zti6WzwsvrjGlPxd6SUqGw3PIJVnCEOwTl8p8eWRbIZmPtvfvzM0WESM5+rMooIEtRh2ypThEZftVRdFb9OVH8aH9Qi8LJW7ytfUQ8FAkLYa5EsRoZFvyycsNIR4zYloUUElSqM80qXQLzSYsd5nmMJH0d+KywMqnB00Ea60TxwB0Kc0eJpL2qVZ2N4QopJF7BWWkOY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
